In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import files
files.upload()

Saving raw_data_unmodified.csv to raw_data_unmodified.csv

{'raw_data_unmodified.csv': b'movie_title,num_critic_for_reviews,duration,DIRECTOR_facebook_likes,actor_3_facebook_likes,ACTOR_1_facebook_likes,gross,num_voted_users,Cast_Total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,ACTOR_2_facebook_likes,imdb_score,title_year\r\nAvatar?\xc3\xbf,723,178,10,855,1000,760505847,886204,4834,,3054,237000000,2009,936,7.9,2009\r\nPirates of the Caribbean: At World\'s End?\xc3\xbf,302,,563,1000,40000,309404152,471220,48350,,1238,300000000,2007,5000,7.1,\r\nSpectre?\xc3\xbf,602,148,20,161,11000,200074175,275868,11700,1,994,245000000,2015,393,6.8,2015\r\nThe Dark Knight Rises?\xc3\xbf,813,,22000,23000,27000,448130642,1144337,106759,,2701,250000000,2012,23000,8.5,\r\nJohn Carter?\xc3\xbf,462,132,"""475""",530,640,73058679,212204,1873,1,738,263700000,2012,632,6.6,\r\nSpider-Man 3?\xc3\xbf,392,156,23,4000,24000,336530303,383056,46055,,1902,258000000,2007,11000,6.2,2007\r\nTangled?\xc3\xbf,324,,15,284,799,200807262,294810,,1,387,260000000,2010,553,7.8,\r\nAvengers: Age of Ultron?\xc3\xbf,635,141,10,19000,26000,458991599,462669,92000,4,1117,250000000,2015,21000,7.5,\r\nAvengers: Age of Ultron?\xc3\xbf,635,141,10,19000,26000,458991599,462669,92000,4,1117,250000000,2015,21000,7.5,2015\r\nHarry Potter and the Half-Blood Prince?\xc3\xbf,375,153,282,10000,25000,301956980,321795,58753,3,973,250000000,2009,11000,7.5,\r\nBatman v Superman: Dawn of Justice?\xc3\xbf,673,183,,2000,15000,330249062,,24450,,3018,250000000,2016,,6.9,2016\r\nSuperman Returns?\xc3\xbf,434,169,,903,18000,200069408,240396,,2,2367,209000000,2006,10000,6.1,\r\nQuantum of Solace?\xc3\xbf,403,106,395,393,451,168368427,330784,2023,1,1243,200000000,2008,412,6.7,2008\r\nPirates of the Caribbean: Dead Man\'s Chest?\xc3\xbf,313,151,563,1000,40000,423032628,522040,48486,2,1832,225000000,2006,5000,7.3,2008\r\n'}

In [ ]:
df = pd.read_csv('/content/raw_data_unmodified.csv')

In [ ]:
df.head()

,movie_title,num_critic_for_reviews,duration,DIRECTOR_facebook_likes,actor_3_facebook_likes,ACTOR_1_facebook_likes,gross,num_voted_users,Cast_Total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,ACTOR_2_facebook_likes,imdb_score,title_year.1
0,Avatar?ÿ,723,178.0,10,855,1000,760505847,886204.0,4834.0,NaN,3054,237000000,2009,936.0,7.9,2009.0
1,Pirates of the Caribbean: At World's End?ÿ,302,NaN,563,1000,40000,309404152,471220.0,48350.0,NaN,1238,300000000,2007,5000.0,7.1,NaN
2,Spectre?ÿ,602,148.0,20,161,11000,200074175,275868.0,11700.0,1.0,994,245000000,2015,393.0,6.8,2015.0
3,The Dark Knight Rises?ÿ,813,NaN,22000,23000,27000,448130642,1144337.0,106759.0,NaN,2701,250000000,2012,23000.0,8.5,NaN
4,John Carter?ÿ,462,132.0,"""475""",530,640,73058679,212204.0,1873.0,1.0,738,263700000,2012,632.0,6.6,NaN

In [ ]:
df.isnull()

,movie_title,num_critic_for_reviews,duration,DIRECTOR_facebook_likes,actor_3_facebook_likes,ACTOR_1_facebook_likes,gross,num_voted_users,Cast_Total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,ACTOR_2_facebook_likes,imdb_score,title_year.1
0,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False
1,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,True
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,True
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
5,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False
6,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,True
7,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
8,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
10,False,False,False,True,False,False,False,True,False,True,False,False,False,True,False,False
11,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,True
12,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.isnull().sum()

movie_title                  0
num_critic_for_reviews       0
duration                     3
DIRECTOR_facebook_likes      2
actor_3_facebook_likes       0
ACTOR_1_facebook_likes       0
gross                        0
num_voted_users              1
Cast_Total_facebook_likes    2
facenumber_in_poster         5
num_user_for_reviews         0
budget                       0
title_year                   0
ACTOR_2_facebook_likes       1
imdb_score                   0
title_year.1                 7
dtype: int64

In [ ]:
missing_data = df.isnull().sum()

df.fillna(0, inplace=True)

df.dropna(inplace=True)

In [ ]:
df.isnull().sum()

movie_title                  0
num_critic_for_reviews       0
duration                     0
DIRECTOR_facebook_likes      0
actor_3_facebook_likes       0
ACTOR_1_facebook_likes       0
gross                        0
num_voted_users              0
Cast_Total_facebook_likes    0
facenumber_in_poster         0
num_user_for_reviews         0
budget                       0
title_year                   0
ACTOR_2_facebook_likes       0
imdb_score                   0
title_year.1                 0
dtype: int64

In [ ]:
df.dtypes

movie_title                   object
num_critic_for_reviews         int64
duration                     float64
DIRECTOR_facebook_likes       object
actor_3_facebook_likes         int64
ACTOR_1_facebook_likes         int64
gross                          int64
num_voted_users              float64
Cast_Total_facebook_likes    float64
facenumber_in_poster         float64
num_user_for_reviews           int64
budget                         int64
title_year                     int64
ACTOR_2_facebook_likes       float64
imdb_score                   float64
title_year.1                 float64
dtype: object

In [ ]:
print(df['DIRECTOR_facebook_likes'].unique())

['10' '563' '20' '22000' '"475"' '23' '15' '282' 0 '395']

In [ ]:
df['DIRECTOR_facebook_likes'] = df['DIRECTOR_facebook_likes'].str.replace('"', '', regex=False).str.strip()
df['DIRECTOR_facebook_likes'].fillna(0, inplace=True)

<ipython-input-27-149bdc843595>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['DIRECTOR_facebook_likes'].fillna(0, inplace=True)

In [ ]:
print(df['DIRECTOR_facebook_likes'].unique())

['10' '563' '20' '22000' '475' '23' '15' '282' 0 '395']

In [ ]:
df['DIRECTOR_facebook_likes'] = df['DIRECTOR_facebook_likes'].astype(int)

In [ ]:
duplicates = df.duplicated().sum()
duplicates

0

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 16 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   movie_title                14 non-null     object
 1   num_critic_for_reviews     14 non-null     int64
 2   duration                   14 non-null     float64
 3   DIRECTOR_facebook_likes    14 non-null     int64
 4   actor_3_facebook_likes     14 non-null     int64
 5   ACTOR_1_facebook_likes     14 non-null     int64
 6   gross                      14 non-null     int64
 7   num_voted_users            14 non-null     float64
 8   Cast_Total_facebook_likes  14 non-null     float64
 9   facenumber_in_poster       14 non-null     float64
 10  num_user_for_reviews       14 non-null     int64
 11  budget                     14 non-null     int64
 12  title_year                 14 non-null     int64
 13  ACTOR_2_facebook_likes     14 non-null     float64
 14  imdb_score                 14 non-null     float64
 15  title_year.1               14 non-null     float64
dtypes: float64(7), int64(8), object(1)
memory usage: 1.9+ KB
None